// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "msg.proto" (package "CustomData", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { MsgData } from "./ciot/proto/v2/msg_data";
import { Err } from "./ciot/proto/v2/errors";
import { IfaceInfo } from "./ciot/proto/v2/iface";
/**
 * @generated from protobuf message CustomData.CustomData
 */
export interface CustomData {
    /**
     * @generated from protobuf field: string text = 1
     */
    text: string; // Custom text field.
    /**
     * @generated from protobuf field: int32 number = 2
     */
    number: number; // Custom number field.
}
/**
 * Represents an CioT message
 *
 * @generated from protobuf message CustomData.Msg
 */
export interface Msg {
    /**
     * @generated from protobuf field: uint32 id = 1
     */
    id: number; // Message ID.
    /**
     * @generated from protobuf field: Ciot.IfaceInfo iface = 2
     */
    iface?: IfaceInfo; // Interface information.
    /**
     * @generated from protobuf field: Ciot.Err error = 3
     */
    error: Err; // Error code.
    /**
     * @generated from protobuf field: Ciot.MsgData data = 4
     */
    data?: MsgData; // Message data.
    /**
     * @generated from protobuf field: CustomData.CustomData custom_data = 5
     */
    customData?: CustomData; // Custom data field.
}
// @generated message type with reflection information, may provide speed optimized methods
class CustomData$Type extends MessageType<CustomData> {
    constructor() {
        super("CustomData.CustomData", [
            { no: 1, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "number", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CustomData>): CustomData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.text = "";
        message.number = 0;
        if (value !== undefined)
            reflectionMergePartial<CustomData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CustomData): CustomData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string text */ 1:
                    message.text = reader.string();
                    break;
                case /* int32 number */ 2:
                    message.number = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CustomData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string text = 1; */
        if (message.text !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.text);
        /* int32 number = 2; */
        if (message.number !== 0)
            writer.tag(2, WireType.Varint).int32(message.number);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message CustomData.CustomData
 */
export const CustomData = new CustomData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Msg$Type extends MessageType<Msg> {
    constructor() {
        super("CustomData.Msg", [
            { no: 1, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "iface", kind: "message", T: () => IfaceInfo },
            { no: 3, name: "error", kind: "enum", T: () => ["Ciot.Err", Err, "ERR_"] },
            { no: 4, name: "data", kind: "message", T: () => MsgData },
            { no: 5, name: "custom_data", kind: "message", T: () => CustomData }
        ]);
    }
    create(value?: PartialMessage<Msg>): Msg {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.error = 0;
        if (value !== undefined)
            reflectionMergePartial<Msg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Msg): Msg {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 id */ 1:
                    message.id = reader.uint32();
                    break;
                case /* Ciot.IfaceInfo iface */ 2:
                    message.iface = IfaceInfo.internalBinaryRead(reader, reader.uint32(), options, message.iface);
                    break;
                case /* Ciot.Err error */ 3:
                    message.error = reader.int32();
                    break;
                case /* Ciot.MsgData data */ 4:
                    message.data = MsgData.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                case /* CustomData.CustomData custom_data */ 5:
                    message.customData = CustomData.internalBinaryRead(reader, reader.uint32(), options, message.customData);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Msg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).uint32(message.id);
        /* Ciot.IfaceInfo iface = 2; */
        if (message.iface)
            IfaceInfo.internalBinaryWrite(message.iface, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* Ciot.Err error = 3; */
        if (message.error !== 0)
            writer.tag(3, WireType.Varint).int32(message.error);
        /* Ciot.MsgData data = 4; */
        if (message.data)
            MsgData.internalBinaryWrite(message.data, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* CustomData.CustomData custom_data = 5; */
        if (message.customData)
            CustomData.internalBinaryWrite(message.customData, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message CustomData.Msg
 */
export const Msg = new Msg$Type();
